name: pzsvc-wta
channels:
  #- http://192.168.33.90
  - https://proxy:proxy@nexus.devops.geointservices.io/content/sites/beachfront-conda/
  - conda-forge
  - bioconda
  - defaults
dependencies:
- cython
- numpy
- potrace
#- python=2.7.13
- pip
- pypotrace
- libagg=2.5.0
- fiona=1.7.4
- gdal=2.1.3
- gippy
- beachfront
- scikit-image
- scikit-learn
- scipy
- bfalg_wta
- pzsvc-exec

