package:
  name: pzsvc-exec
  version: 0.1.0

source:
  # https://github.com/venicegeo/pzsvc-exec
  path: ../vendor/pzsvc-exec

requirements:
  build:
    #- go

about:
  home: https://github.com/venicegeo/pzsvc-exec
  summary: "Serve command-line programs to Piazza, based on the contents of a config file."
  license: Apache 2.0
